exploring the design a little bit more, avoiding calculators
DevCapu/bee pull request #2
Opened 2021-03-17 00:05 UTC by alexandreaquiles

I tried to avoid calculators and classes that are just wrappers to double values.

2021-03-17 00:14 UTC, alexandreaquiles commented
Sorry. I didn't test if is compiling correctly, as I don't have Android Studio and my IntelliJ didn't work correctly.

2021-03-17 19:07 UTC, DevCapu requested changes
Opa, só deixei uns comentários.

OBS: Nos modelos está faltando o import de `UserInfo`.

2021-03-17 19:07 UTC, DevCapu commented on beeHealthy/src/main/java/br/com/devcapu/bee_healthy/domain/user_info/Objective.java
> +    public Objective(int calorieRatio) {
Esse `public` não compila

2021-03-18 02:51 UTC, DevCapu commented on beeHealthy/src/main/java/br/com/devcapu/bee_healthy/domain/health/BasalEnergyExpenditure.java
>      public double getValue() {
Se a gente deixar o atributo value como public igual nas outras classes podemos remover esse método.

2021-03-19 03:35 UTC, DevCapu approved these changes

2021-03-19 15:02 UTC, merged